name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: cmake -DCMAKE_BUILD_TYPE=Debug .
    - name: make all
      run: make all
    - name: test
      run: make test
